#!/usr/bin/env python3
"""
AI-Powered IaC Generator
Generates Terraform configurations based on simple YAML specifications
"""

import yaml
import json
import sys
import os
from typing import Dict, Any

# This is a simplified version. In production, this would call OpenAI/Anthropic API
# to generate Terraform code based on specifications.


def generate_terraform_module(spec: Dict[str, Any], output_dir: str) -> None:
    """Generate Terraform module from specification"""
    
    service_name = spec.get('name', 'service')
    cloud_provider = spec.get('cloud_provider', 'aws')
    instance_type = spec.get('instance_type', 't3.medium')
    replicas = spec.get('replicas', 2)
    
    # Generate main.tf
    main_tf = f'''# Auto-generated Terraform module for {service_name}
# Generated by AI IaC Generator

variable "region" {{
  description = "Cloud provider region"
  type        = string
  default     = "us-east-1"
}}

variable "environment" {{
  description = "Environment name"
  type        = string
  default     = "production"
}}

resource "kubernetes_deployment" "{service_name}" {{
  metadata {{
    name = "{service_name}"
    labels = {{
      app = "{service_name}"
    }}
  }}

  spec {{
    replicas = {replicas}

    selector {{
      match_labels = {{
        app = "{service_name}"
      }}
    }}

    template {{
      metadata {{
        labels = {{
          app = "{service_name}"
        }}
      }}

      spec {{
        container {{
          name  = "{service_name}"
          image = "${{var.image}}:${{var.tag}}"

          resources {{
            requests = {{
              memory = "256Mi"
              cpu    = "250m"
            }}
            limits = {{
              memory = "512Mi"
              cpu    = "500m"
            }}
          }}
        }}
      }}
    }}
  }}
}}

resource "kubernetes_service" "{service_name}" {{
  metadata {{
    name = "{service_name}"
  }}

  spec {{
    selector = {{
      app = "{service_name}"
    }}

    port {{
      port        = 80
      target_port = 8000
    }}

    type = "LoadBalancer"
  }}
}}
'''
    
    # Write to file
    os.makedirs(output_dir, exist_ok=True)
    with open(f"{output_dir}/main.tf", "w") as f:
        f.write(main_tf)
    
    print(f"✅ Generated Terraform module for {service_name} in {output_dir}/main.tf")


def main():
    if len(sys.argv) < 2:
        print("Usage: python ai-iac-generator.py <spec-file.yaml> [output-dir]")
        sys.exit(1)
    
    spec_file = sys.argv[1]
    output_dir = sys.argv[2] if len(sys.argv) > 2 else "generated-terraform"
    
    # Load specification
    with open(spec_file, 'r') as f:
        spec = yaml.safe_load(f)
    
    # Generate Terraform
    generate_terraform_module(spec, output_dir)
    print(f"\n✅ Terraform module generated successfully!")
    print(f"📁 Output directory: {output_dir}")


if __name__ == "__main__":
    main()

